//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer_Basic> Answer_Basic { get; set; }
        public virtual DbSet<ClinicPeriod> ClinicPeriod { get; set; }
        public virtual DbSet<FinishQA> FinishQA { get; set; }
        public virtual DbSet<LockClinicPeriod> LockClinicPeriod { get; set; }
        public virtual DbSet<MailBasic> MailBasic { get; set; }
        public virtual DbSet<MailCcs> MailCcs { get; set; }
        public virtual DbSet<MailGroup> MailGroup { get; set; }
        public virtual DbSet<MailTos> MailTos { get; set; }
        public virtual DbSet<NewTb> NewTb { get; set; }
        public virtual DbSet<PFTarget> PFTarget { get; set; }
        public virtual DbSet<Question_Basic> Question_Basic { get; set; }
        public virtual DbSet<SwitchAccountsLog> SwitchAccountsLog { get; set; }
        public virtual DbSet<sysHospital> sysHospital { get; set; }
    }
}
