//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishQA
    {
        public long Id { get; set; }
        public string member { get; set; }
        public string UID { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<System.DateTime> lastEditTime { get; set; }
        public string Note { get; set; }
        public string Clinic { get; set; }
        public string QuesionId { get; set; }
    }
}
