//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockClinicPeriod
    {
        public System.Guid MSRowid { get; set; }
        public string MSHospID { get; set; }
        public string MSCode { get; set; }
        public string MSDrId { get; set; }
        public string MSDrBNO { get; set; }
        public string MSDrName { get; set; }
        public string MSHISDate { get; set; }
        public string MSRegSection { get; set; }
        public string MSKind { get; set; }
        public Nullable<int> MSPeople { get; set; }
        public string MSFirstOrNot { get; set; }
        public Nullable<int> MSTotalMoney { get; set; }
    }
}
