//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFTarget
    {
        public string PFTRowid { get; set; }
        public string PFTHospID { get; set; }
        public int PFTYear { get; set; }
        public int PFTMonth { get; set; }
        public int PFTLValue { get; set; }
        public int PFTHValue { get; set; }
        public Nullable<bool> C3lock { get; set; }
    }
}
