//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwitchAccountsLog
    {
        public string Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<System.DateTime> clsTime { get; set; }
        public string clsUserId { get; set; }
        public Nullable<System.DateTime> opnTime { get; set; }
        public string opnUserId { get; set; }
    }
}
