//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysHospital
    {
        public string HospRowid { get; set; }
        public int HospSeq { get; set; }
        public string HospID { get; set; }
        public string HospName { get; set; }
        public string HospBID { get; set; }
        public string HospBName { get; set; }
        public string HospUniformNo { get; set; }
        public string HospPrincipal { get; set; }
        public string HospDean { get; set; }
        public string HospAddress { get; set; }
        public string HospAreaCode { get; set; }
        public string HospPhone { get; set; }
        public string HospFaxno { get; set; }
        public string HospEmail { get; set; }
        public string HospLevel { get; set; }
        public string HospHIS { get; set; }
        public Nullable<bool> HospActive { get; set; }
        public string HospImage { get; set; }
        public string HospRegSys { get; set; }
        public string HospLogo { get; set; }
        public string HospQRCode01 { get; set; }
        public string HospQRCode02 { get; set; }
        public string HospRTId { get; set; }
        public string HospIPAddress { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
